version: "3.8"

x-default-logs: &default-opts
  logging:
    options:
      max-size: "1m"

x-master-opts: &master
  ES_JAVA_OPTS: "-Xmx4g -Xms4g -XX:+UnlockExperimentalVMOptions"
  discovery.seed_resolver.timeout: 60s
  discovery.seed_hosts: master1,master2,master3
  cluster.initial_master_nodes: master1,master2,master3
  cluster.name: "es-cluster"
  network.host: 0.0.0.0
  node.master: "true"
  node.data: "false"
  node.ingest: "false"

x-data-opts: &data
  ES_JAVA_OPTS: "-Xmx32g -Xms32g -XX:MaxDirectMemorySize=16g -XX:+UnlockExperimentalVMOptions"
  discovery.seed_resolver.timeout: 60s
  discovery.seed_hosts: master1,master2,master3
  cluster.initial_master_nodes: master1,master2,master3
  cluster.name: "es-cluster"
  network.host: 0.0.0.0
  node.master: "false"
  node.data: "true"
  node.ingest: "false"

services:

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:latest
    hostname: swarm-listener
    networks:
      - elastic
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  proxy:
    image: dockerflow/docker-flow-proxy:latest
    hostname: proxy
    ports:
      - "80:80"
      - "443:443"
      - "9200:9200"
      - "8200:8200"
    networks:
      - elastic
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - BIND_PORTS=9200,8200
    deploy:
      replicas: 2

  master1:
    image: atsip/elkdocker:usedesk
    hostname: master1
    environment:
      - node.name=master1
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=${INITIAL_MASTER_NODES:-elastic-master01}
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=usedesk
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.balance.index=0.45f
      - cluster.routing.allocation.balance.shard=5.15f
      - cluster.routing.allocation.balance.threshold=0.3f
      - cluster.routing.use_adaptive_replica_selection=true
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - esmaster1:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.master1 ==  true]
      endpoint_mode: dnsrr
      mode: 'replicated'
      replicas: 1
      resources:
        limits:
          memory: 8G

  master2:
    image: atsip/elkdocker:usedesk
    hostname: master2
    environment:
      - node.name=master2
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=${INITIAL_MASTER_NODES:-elastic-master01}
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=usedesk
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.balance.index=0.45f
      - cluster.routing.allocation.balance.shard=5.15f
      - cluster.routing.allocation.balance.threshold=0.3f
      - cluster.routing.use_adaptive_replica_selection=true
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - esmaster2:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.master2 ==  true]
      endpoint_mode: dnsrr
      mode: 'replicated'
      replicas: 1
      resources:
        limits:
          memory: 8G
      
  master3:
    image: atsip/elkdocker:usedesk
    hostname: master3
    environment:
      - node.name=master3
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=${INITIAL_MASTER_NODES:-elastic-master01}
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=usedesk
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.balance.index=0.45f
      - cluster.routing.allocation.balance.shard=5.15f
      - cluster.routing.allocation.balance.threshold=0.3f
      - cluster.routing.use_adaptive_replica_selection=true
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - esmaster3:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.master3 ==  true]
      endpoint_mode: dnsrr
      mode: 'replicated'
      replicas: 1
      resources:
        limits:
          memory: 8G

  elasticsearch1:
    image: atsip/elkdocker:usedesk
    hostname: data1
    environment:
      - node.name=data1
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=${INITIAL_MASTER_NODES:-elastic-master01}
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=usedesk
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.balance.index=0.45f
      - cluster.routing.allocation.balance.shard=5.15f
      - cluster.routing.allocation.balance.threshold=0.3f
      - cluster.routing.use_adaptive_replica_selection=true
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - /data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.data1 ==  true]
      mode: 'replicated'
      replicas: 1
#      resources:
#        limits:
#          memory: 64G
      endpoint_mode: dnsrr
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
        - com.df.srcPort=9200

  elasticsearch2:
    image: atsip/elkdocker:usedesk
    hostname: data2
    environment:
      - node.name=data2
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=${INITIAL_MASTER_NODES:-elastic-master01}
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=usedesk
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.balance.index=0.45f
      - cluster.routing.allocation.balance.shard=5.15f
      - cluster.routing.allocation.balance.threshold=0.3f
      - cluster.routing.use_adaptive_replica_selection=true
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - /data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.data2 ==  true]
      mode: 'replicated'
      replicas: 1
#      resources:
#        limits:
#          memory: 64G
      endpoint_mode: dnsrr
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
        - com.df.srcPort=9200
  
  elasticsearch3:
    image: atsip/elkdocker:usedesk
    hostname: data3
    environment:
      - node.name=data3
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=${INITIAL_MASTER_NODES:-elastic-master01}
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=usedesk
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.balance.index=0.45f
      - cluster.routing.allocation.balance.shard=5.15f
      - cluster.routing.allocation.balance.threshold=0.3f
      - cluster.routing.use_adaptive_replica_selection=true
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - /data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.data3 ==  true]
      mode: 'replicated'
      replicas: 1
#      resources:
#        limits:
#          memory: 64G
      endpoint_mode: dnsrr
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
        - com.df.srcPort=9200

  elasticsearch4:
    image: atsip/elkdocker:usedesk
    hostname: data4
    environment:
      - node.name=data1
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=${INITIAL_MASTER_NODES:-elastic-master01}
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=usedesk
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.balance.index=0.45f
      - cluster.routing.allocation.balance.shard=5.15f
      - cluster.routing.allocation.balance.threshold=0.3f
      - cluster.routing.use_adaptive_replica_selection=true
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - /data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.data4 ==  true]
      mode: 'replicated'
      replicas: 1
#      resources:
#        limits:
#          memory: 64G
      endpoint_mode: dnsrr
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
        - com.df.srcPort=9200

  elasticsearch5:
    image: atsip/elkdocker:usedesk
    hostname: data5
    environment:
      - node.name=data5
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=${INITIAL_MASTER_NODES:-elastic-master01}
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=usedesk
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.balance.index=0.45f
      - cluster.routing.allocation.balance.shard=5.15f
      - cluster.routing.allocation.balance.threshold=0.3f
      - cluster.routing.use_adaptive_replica_selection=true
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - /data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.data5 ==  true]
      mode: 'replicated'
      replicas: 1
#      resources:
#        limits:
#          memory: 64G
      endpoint_mode: dnsrr
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
        - com.df.srcPort=9200

  elasticsearch6:
    image: atsip/elkdocker:usedesk
    hostname: data6
    environment:
      - node.name=data6
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=${INITIAL_MASTER_NODES:-elastic-master01}
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=usedesk
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.balance.index=0.45f
      - cluster.routing.allocation.balance.shard=5.15f
      - cluster.routing.allocation.balance.threshold=0.3f
      - cluster.routing.use_adaptive_replica_selection=true
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - /data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.data6 ==  true]
      mode: 'replicated'
      replicas: 1
#      resources:
#        limits:
#          memory: 64G
      endpoint_mode: dnsrr
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
        - com.df.srcPort=9200

  logstash:
    image: logstash:${ELASTIC_VERSION:-7.17.6}
    hostname: "{{.Node.Hostname}}-logstash"
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-usedesk}
    ports:
      - "12201:12201/udp"
    networks:
      - elastic
    configs:
      - source: ls_config
        target: /usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: kibana:${ELASTIC_VERSION:-7.17.6}
    hostname: "{{.Node.Hostname}}-kibana"
    environment:
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
      - csp.strict=true
      - xpack.encryptedSavedObjects.encryptionKey=Ghtg56pqvbcnthGbnRbyDnskeDhdfThjEdl
      - status.allowAnonymous=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=usedesk
      - SERVER_NAME="{{.Node.Hostname}}-kibana"
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - kibana:/usr/share/kibana/data
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=5601
        - com.df.srcPort=80
  
  apm-server:
    image: elastic/apm-server:${ELASTIC_VERSION:-7.17.6}
    hostname: "{{.Node.Hostname}}-apm-server"
    networks:
      - elastic
    command: > 
        --strict.perms=false -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.kibana.username=${ELASTICSEARCH_USERNAME:-elastic}
        -E setup.kibana.password=${ELASTICSEARCH_PASSWORD:-usedesk}
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E apm-server.kibana.username=${ELASTICSEARCH_USERNAME:-elastic}
        -E apm-server.kibana.password=${ELASTICSEARCH_PASSWORD:-usedesk}
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
        -E output.elasticsearch.username=${ELASTICSEARCH_USERNAME:-elastic}
        -E output.elasticsearch.password=${ELASTICSEARCH_PASSWORD:-usedesk}
        -E xpack.monitoring.enabled=true
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=8200
        - com.df.srcPort=8200
      
networks:
    elastic:
      external: true

volumes:
  kibana:
  esmaster1:
  esmaster2:
  esmaster3:

configs:
  ls_config:
    file: $PWD/elk/logstash/config/pipeline/logstash.conf
