ARG ELK_VERSION
FROM elasticsearch:${ELK_VERSION}
#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3
COPY elastic-stack-ca.p12 /usr/share/elasticsearch/config/elastic-stack-ca.p12